### PR TITLE
Make cookbook compatible with Chef 16

### PR DESCRIPTION
**Pull request by asvinours**
All tests are passing with kitchen and vagrant with  Chef 16.2.73

### CODE REVIEW

**Comment by petracvv** [comment]
Thanks for the PR! I haven't looked at this project for a while so it was out of date with respect to Chef versions and testing. I updated the circle ci config so that it will test against the latest Chef now.

Could you rebase so I can see the tests running here?

**Comment by petracvv** [comment]
Nevermind that, forgot I can do the rebase myself in Github

**Comment by petracvv** [comment]
Ok. Looks good except for one of the Chefspec tests failing. Switching the following lines https://github.com/petracvv/logstash_lwrp/blob/a7ee429e5c72940860b029b63e4e3cd28b0544cb/spec/install_spec.rb#L68-L69
to mention the new notify_group resource instead of the log resource should fix that.

Also, could you please add a changelog entry?

**Comment by asvinours** [comment]
I have added a changelog entry.
There was 2 rspec tests failing, but I couldn't find any information on how to replace the first one testing the log output with the new notify_group resource. So I removed it. I fixed the second rspec test

**Comment by petracvv** [comment]
Looks good! Some tests are not passing because of some new platforms I added. I'll merge and clean that up afterwards.

Hopefully I'll get time to do that and make release this week.

**Pull request merged**
