### PR TITLE
 Add pipeline template variables

### PR DESCRIPTION
**Pull request by axelrtgs**
Added feature from to do list for allowing template variables in pipeline configs

- Linting Passes
- Tests pass
- Foodcritic passes
- Changelog updated
- Version bumped

### CODE REVIEW

**Comment by axelrtgs** [comment]
Could you please review, approve, merge and release to supermarket. I could really use this new functionality for a project i am working on so i am eager to see it pushed through.

**Comment by petracvv** [comment]
Looks good! Thanks for the PR. I'll look at publishing a new version to supermarket in the next few days.

**Comment by petracvv** [comment]
New version published. Enjoy!

**Comment by axelrtgs** [comment]
Thank you very much :)

**Pull request merged**
