### PR TITLE
bugfix: YAML gem is no longer loaded by default

### PR DESCRIPTION
**Pull request by axelrtgs**
YAML gem is no longer loaded by default so i used the YAML.dump method as recommended by Chef

### CODE REVIEW

**Comment by petracvv** [comment]
Thanks for the PR! Looks like Chef finally got rid of foodcritic so the tests here are failing. Do you mind changing the following line in .delivery/project.toml from:
```
syntax = "foodcritic ."
```
to
```
syntax = "echo skipping"
```

and adding it to this PR? That should get the tests running on github again.

**Comment by axelrtgs** [comment]
I also had to adjust for YAML.dump splitting one of the longer json strings but i validated that the output was indeed correct YAML and the JSON representation was the intended one:
image

**Comment by axelrtgs** [comment]
Tests run and pass locally
```
Instance             Driver   Provisioner  Verifier  Transport  Last Action  Last Error
default-ubuntu-1604  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
default-ubuntu-1804  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
default-ubuntu-2004  Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
default-debian-9     Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
default-centos-7     Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
default-centos-8     Vagrant  ChefZero     Inspec    Ssh        Verified     <None>
```

**Comment by petracvv** [comment]
I merged this by hand. There is some issue on 16.04 in the test that is unrelated to this PR. Support for that ends in a month or 2 anyways so I'll probably just remove it from tested platforms in the future

**Comment by axelrtgs** [comment]
Thanks for merging this

**Comment by petracvv** [comment]
Yeah, sure. I'll look at making a release on supermarket in the next few days

**Pull request merged**
